---
# tasks file for roles/install_nagios

  - name: Installing pre-requisites
    apt:
      name:
        - autoconf
        - gcc
        - libc6
        - make
        - wget
        - unzip
        - apache2
        - apache2-utils
        - php5
        - libgd2-xpm-dev
      state: latest
      update_cache: yes

  - name: Stop Firewall
    service:
      name: ufw
      state: stopped
      enabled: no

  - name: Download and unachive
    unarchive:
      src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
      dest: /tmp/
      remote_src: yes
    register: nagios_source

  - name: Create Make file
    shell: cd /tmp/nagioscore-nagios-4.4.5; sh /tmp/nagioscore-nagios-4.4.5/configure --with-httpd-conf=/etc/apache2/sites-enabled
    register: make_file
    when: nagios_source.changed

  - name: Compile from source
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5/
      target: all
    become: yes
    when: make_file.changed

  - name: Create user and group
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5
      target: install-groups-users
    become: yes
    when: make_file.changed

  - name: Add www-dataa user to nagios group
    user:
      name: www-data
      groups: nagios
      append: yes

  - name: Install binaries
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5
      target: install
    become: yes
    when: make_file.changed

  - name: Install service/daemon
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5
      target: install-daemoninit
    become: yes
    when: make_file.changed

  - name: Install command mode
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5
      target: install-commandmode
    become: yes
    when: make_file.changed

  - name: install configuration files
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5
      target: install-config
    become: yes
    when: make_file.changed

  - name: Install Apache config files
    make:
      chdir: /tmp/nagioscore-nagios-4.4.5
      target: install-webconf
    become: yes
    when: make_file.changed
    register: install_webconf

  - name: Enable rewrite module
    apache2_module:
      state: present
      name: rewrite

  - name: Enable cgi module
    apache2_module:
      state: present
      name: cgi

  - name: Restart apache2
    service:
      name: apache2
      state: restarted
    when: install_webconf.changed

  - name: Start and enable nagios
    service:
      name: nagios
      state: started
      enables: yes
    when: install_webconf.changed
