---
# tasks file for roles/install_prometheus
  - name: Installing nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Starting nginx
    service:
      name: nginx
      state: started

  - name: Creating /etc/prometheus
    file:
      path: /etc/prometheus
      state: directory
      mode: '0755'

  - name: Creating /var/lib/prometheus
    file: 
      path: /var/lib/prometheus
      state: directory
      mode: '0755'

  - name: Creating /var/log/prometheus
    file:
      path: /var/log/prometheus
      state: directory
      mode: '0755'

  - name: Creating /var/run/prometheus
    file:
      path: /var/run/prometheus
      state: directory
      mode: '0755'

  - name: Unarchive Prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v2.2.1/promethus-2.2.1.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes
    register: prometheus_download

  - name: Copying Promethues to /usr/local/bin
    shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus /usr/local/bin/"
    when: prometheus_download.changed

  - name: Copying Promtool to usr/local/bin
    shell: "cp /tmp/prometheus-2.2.1.linux-amd64/promtool /usr/local/bin/"
    when: prometheus_download.changed

  - name: Prometheus executable
    file:
      path: /usr/local/bin/prometheus
      mode: u+x,g+x,o+x

  - name: Promtool exacutable
    file:
      path: /usr/local/bin/promtool
      mode: u+x,g+x,o+x

  - name: Copying Prometheus.yml to /etc/prometheus
    shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus.yml /etc/prometheus/"
    when: prometheus_download.changed

  - name: Copying consoles to /etc/prometheus
    shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/consoles /etc/prometheus/"
    when: prometheus_download.changed

  - name: Copying console_lib to /etc/prometheus
    shell: "cp -r /tmp/prometheus-2.2.1linux-amd64/console_libraries /etc/prometheus/"
    when: prometheus_download.changed

  - name: Copying prometheus.service
    copy:
      src: prometheus.service
      dest: /etc/systemd/system/prometheus.service
      mode: '0755'

  - name: Stop ufw
    service: 
      name: ufw
      state: stopped
      enabled: no

  - name: Starting Prometheus
    service:
      name: prometheus
      state: started
      enabled: yes
 
